version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    env_file: .env
    image: amartini1985/foodgram_backend
    volumes:
      - static:/app/collected_static
      - media:/var/www/backend/media
    depends_on:
      - db 

  frontend:
    env_file: .env
    image: amartini1985/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    env_file: .env
    container_name: foodgram-proxy
    image: amartini1985/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/var/www/backend/media
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
