version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data


  backend:
    env_file: .env
    build: ./backend
    volumes:
      - static:/app/collected_static
      - media:/var/www/backend/media
    depends_on:
      - db 

  frontend:
    env_file: .env
    container_name: foodgram-front
    build: ./frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    env_file: .env
    container_name: foodgram-proxy
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/var/www/backend/media
      - ../frontend/build:/usr/share/nginx/html
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend 



      
      

