version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    env_file: ../.env
    container_name: foodgram-front
    image: amartini1985/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/


  backend:
    env_file: ../.env
    image: amartini1985/foodgram_backend
    volumes:
      - media:/var/www/backend/media    
    depends_on:
      - db 

  nginx:
    container_name: foodgram-proxy
    #image: nginx:1.25.4-alpine
    image: amartini1985/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - media:/var/www/backend/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
