# Generated by Django 4.2.19 on 2025-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_favoriterecipe_unique_user_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcartrecipe',
            name='unique_shoppingcart_recipe',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_user_favoriterecipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_user_shoppingcartrecipe'),
        ),
    ]
