# Generated by Django 4.2.19 on 2025-03-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
