# Generated by Django 4.2.19 on 2025-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('following')), _negated=True), name='deny_self_subscription'),
        ),
    ]
